### ISSUE TITLE
不成熟的小建议

### ISSUE THREAD

**Issue by zcdliuwei** [calmisential/CenterNet_TensorFlow2#2]
您好，我看您使用TensorFlow2复现了很多经典流行的框架，因为我也使用TF2，看到您的复现代码很有兴趣，我试着用了一下您的SSD和centernet，存在的问题是，训练非常缓慢，而且效果不能保证，其中SSD的损失从一个异常的极大值缓慢下降，后来又变得非常大，这肯定是有问题的，centernet训练到50轮倒是没有出现损失值突然暴增的情况，但是训练很慢，我是在公共数据集（VOC）上训练的，然后使用预训练的模型在自有数据集上随便测试几张，效果非常差，当使用其他在VOC或者COCO上预训练的模型，比如yolo或者mask rcnn进行相同测试的时候，效果已经很惊艳，给我的感觉是，您的模型即使在自有数据集上训练，效果也很难保证，我对这些网络结构谈不上非常了解，但我认为您的复现应该是存在问题的，或许有理解不到的地方，建议大佬重新看看代码，是不是有未解决的问题 ？

**Comment by calmiLovesAI** [comment]
嗯嗯， SSD那个代码确实是有问题的，我会重新写一遍。你说CenterNet在VOC上训练之后再在其他数据上测试，效果很差，这个可能是训练次数不够的原因，只要是在VOC上训练然后在VOC上测试，发现效果是可以的，那就说明CenterNet的代码是没问题的。
